version: '3.8'

services:
  app:
    image: progan:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/progan_database

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: progan_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password